from tkinter import *
root = Tk()
frame = Frame(root)
frame.pack()
topframe=Frame(root)
topframe.pack(side=TOP)
bottomframe = Frame(root)
bottomframe.pack(side=BOTTOM)
redbutton = Button(topframe, text="Red", fg="red")
redbutton.pack(side=TOP)
greenbutton = Button(frame, text="Green", fg="green")
greenbutton.pack(side=LEFT)
bluebutton = Button(frame, text="Blue", fg="blue")
bluebutton.pack(side=LEFT)
brownbutton = Button(bottomframe, text="Brown", fg="brown")
brownbutton.pack(side=BOTTOM)
root.mainloop()
